global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: telegraf
    static_configs:
      - targets: ["telegraf:9273"]

  - job_name: agents
    static_configs:
      - targets: ["agent-1:9100"]
        labels: { agent: "1", group: "edge" }
      - targets: ["agent-2:9100"]
        labels: { agent: "2", group: "cloud" }
      - targets: ["agent-3:9100"]
        labels: { agent: "3", group: "cloud" }

  - job_name: litellm
    static_configs:
      - targets: ["litellm-1:4000"]
        labels: { agent: "1", group: "edge" }
      - targets: ["litellm-2:4000"]
        labels: { agent: "2", group: "cloud" }
      - targets: ["litellm-3:4000"]
        labels: { agent: "3", group: "cloud" }
    metrics_path: /metrics

  - job_name: toxiproxy
    metrics_path: /metrics
    static_configs:
      - targets: ["toxiproxy-1:8474"]
        labels: { agent: "1", group: "edge" }
      - targets: ["toxiproxy-2:8474"]
        labels: { agent: "2", group: "cloud" }
      - targets: ["toxiproxy-3:8474"]
        labels: { agent: "3", group: "cloud" }
