[agent]
  interval = "5s"
  flush_interval = "5s"
  hostname = "telegraf"
  omit_hostname = false

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2

[[inputs.docker]]
  endpoint = "tcp://docker-proxy:2375"
  gather_services = false
  perdevice = false
  total = true
  docker_label_include = ["group"]
  timeout = "10s"
